var Mustache=function(){var j=function(){};j.prototype={otag:"{{",ctag:"}}",pragmas:{},buffer:[],pragmas_implemented:{"IMPLICIT-ITERATOR":!0},context:{},render:function(a,b,d,c){if(!c)this.context=b,this.buffer=[];if(!this.includes("",a))if(c)return a;else{this.send(a);return}a=this.render_pragmas(a);a=this.render_section(a,b,d);if(c)return this.render_tags(a,b,d,c);this.render_tags(a,b,d,c)},send:function(a){a!=""&&this.buffer.push(a)},render_pragmas:function(a){if(!this.includes("%",a))return a;
var b=this;return a.replace(RegExp(this.otag+"%([\\w-]+) ?([\\w]+=[\\w]+)?"+this.ctag),function(a,c,e){if(!b.pragmas_implemented[c])throw{message:"This implementation of mustache doesn't understand the '"+c+"' pragma"};b.pragmas[c]={};e&&(a=e.split("="),b.pragmas[c][a[0]]=a[1]);return""})},render_partial:function(a,b,d){a=this.trim(a);if(!d||d[a]===void 0)throw{message:"unknown_partial '"+a+"'"};return typeof b[a]!="object"?this.render(d[a],b,d,!0):this.render(d[a],b[a],d,!0)},render_section:function(a,
b,d){if(!this.includes("#",a)&&!this.includes("^",a))return a;var c=this;return a.replace(RegExp(this.otag+"(\\^|\\#)\\s*(.+)\\s*"+this.ctag+"\n*([\\s\\S]+?)"+this.otag+"\\/\\s*\\2\\s*"+this.ctag+"\\s*","mg"),function(a,g,i,f){a=c.find(i,b);if(g=="^")return!a||c.is_array(a)&&a.length===0?c.render(f,b,d,!0):"";else if(g=="#")return c.is_array(a)?c.map(a,function(a){return c.render(f,c.create_context(a),d,!0)}).join(""):c.is_object(a)?c.render(f,c.create_context(a),d,!0):typeof a==="function"?a.call(b,
f,function(a){return c.render(a,b,d,!0)}):a?c.render(f,b,d,!0):""})},render_tags:function(a,b,d,c){for(var e=this,g=function(){return RegExp(e.otag+"(=|!|>|\\{|%)?([^\\/#\\^]+?)\\1?"+e.ctag+"+","g")},i=g(),f=function(a,c,f){switch(c){case "!":return"";case "=":return e.set_delimiters(f),i=g(),"";case ">":return e.render_partial(f,b,d);case "{":return e.find(f,b);default:return e.escape(e.find(f,b))}},a=a.split("\n"),h=0;h<a.length;h++)a[h]=a[h].replace(i,f,this),c||this.send(a[h]);if(c)return a.join("\n")},
set_delimiters:function(a){a=a.split(" ");this.otag=this.escape_regex(a[0]);this.ctag=this.escape_regex(a[1])},escape_regex:function(a){if(!arguments.callee.sRE)arguments.callee.sRE=RegExp("(\\/|\\.|\\*|\\+|\\?|\\||\\(|\\)|\\[|\\]|\\{|\\}|\\\\)","g");return a.replace(arguments.callee.sRE,"\\$1")},find:function(a,b){var a=this.trim(a),d;b[a]===!1||b[a]===0||b[a]?d=b[a]:(this.context[a]===!1||this.context[a]===0||this.context[a])&&(d=this.context[a]);return typeof d==="function"?d.apply(b):d!==void 0?
d:""},includes:function(a,b){return b.indexOf(this.otag+a)!=-1},escape:function(a){return String(a===null?"":a).replace(/&(?!\w+;)|["'<>\\]/g,function(a){switch(a){case "&":return"&amp;";case "\\":return"\\\\";case '"':return"&quot;";case "'":return"&#39;";case "<":return"&lt;";case ">":return"&gt;";default:return a}})},create_context:function(a){if(this.is_object(a))return a;else{var b=".";if(this.pragmas["IMPLICIT-ITERATOR"])b=this.pragmas["IMPLICIT-ITERATOR"].iterator;var d={};d[b]=a;return d}},
is_object:function(a){return a&&typeof a=="object"},is_array:function(a){return Object.prototype.toString.call(a)==="[object Array]"},trim:function(a){return a.replace(/^\s*|\s*$/g,"")},map:function(a,b){if(typeof a.map=="function")return a.map(b);else{for(var d=[],c=a.length,e=0;e<c;e++)d.push(b(a[e]));return d}}};return{name:"mustache.js",version:"0.3.1-dev",to_html:function(a,b,d,c){var e=new j;if(c)e.send=c;e.render(a,b,d);if(!c)return e.buffer.join("\n")}}}();
(function(){'use strict';var f=void 0,j=null,ca=this;function da(a,b){var c=a.split("."),d=window||ca;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==f?d[e]=b:d=d[e]?d[e]:d[e]={}}var p=Date.now||function(){return+new Date};var ea,fa,ga=[],ha={},ia=j;function ja(){var a=p();ga.forEach(function(b,c){if(ea&&!b.Sb&&(!ia||b.name&&ia.indexOf(b.name)!==-1)&&!(a-b.pb<=b.mc)){b.pb=a;b.Ab-=1;if(b.Ab<=0&&(!b.Mb||b.Ab<0))if(ka(ga,c),delete ha[b.name],b.Mb)return;b.kc.apply(b.rc,b.dc)}});ga.length||la()}function ma(a,b,c,d,e,g){var i=p(),n=e?ha[e]:j;n||(n={kc:a,name:e,rc:g,pb:i},ga.push(n),e&&(ha[e]=n));n.dc=d||[];n.Ab=c;n.mc=Math.max(b,25);n.Mb=!1;n.Sb=!1;ea||(ea=window.setInterval(ja,25))}
function na(a,b,c,d,e){ma(a,b,1,c,d,e)}function oa(a,b,c){ma(a,100,Infinity,b,c,f)}function pa(a,b,c,d){ma(a,0,1,b,c,d)}function qa(a,b){ia=a;b&&(fa=setTimeout(ra,b))}function ra(){ia=j;fa&&(window.clearTimeout(fa),fa=j)}function sa(a){delete ha[a];ga.forEach(function(b,c){if(b.name===a)ka(ga,c),b.Sb=!0})}function la(){ea&&window.clearInterval(ea);ra();ea=j;ga=[];ha={}};p();if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){for(var c=0,d=this.length;c<d;c+=1)c in this&&a.call(b,this[c],c,this)};if(!Array.prototype.some)Array.prototype.some=function(a,b){for(var c=0,d=this.length;c<d;c+=1)if(c in this&&a.call(b,this[c],c,this))return!0;return!1};if(!Array.prototype.every)Array.prototype.every=function(a,b){for(var c=0,d=this.length;c<d;c+=1)if(c in this&&!a.call(b,this[c],c,this))return!1;return!0};
if(!Array.prototype.map)Array.prototype.map=function(a,b){for(var c=0,d=this.length,e=[];c<d;c+=1)c in this&&(e[c]=a.call(b,this[c],c,this));return e};if(!Array.prototype.filter)Array.prototype.filter=function(a,b){for(var c=0,d,e=this.length,g=[];c<e;c+=1)c in this&&(d=this[c],a.call(b,d,c,this)&&g.push(d));return g};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){var c,d;for(c=b||0,d=this.length;c<d;c+=1)if(this[c]===a)return c;return-1};
if(!Array.isArray)Array.isArray=function(a){return Object.prototype.toString.apply(a)==="[object Array]"};function q(a){return Array.prototype.slice.call(a,0)}function ka(a,b){var c=a.slice(b+1||a.length);a.length=b<0?a.length+b:b;a.push.apply(a,c)}"attachEvent"in document&&(q=function(a){var b,c,d=[];for(b=0,c=a.length;b<c;b+=1)d.push(a[b]);return d});var ta,ua,r=window.navigator.userAgent.toLowerCase(),va=!("localStorage"in window&&"querySelectorAll"in document&&"JSON"in window),wa=document.compatMode!=="BackCompat"&&"XMLHttpRequest"in window&&!(!document.addEventListener&&!document.attachEvent)&&!(!document.documentElement.currentStyle&&!window.getComputedStyle)&&("querySelectorAll"in document||"attachEvent"in document&&!("addEventListener"in document)),xa="documentMode"in document&&document.documentMode<=7,za=ya==="android"||/mobile/.test(r),
Aa=window.screen.width<=600,Ba=/webkit/.test(r)?/chrome|safari/.test(r)?/(chrome|safari)/.exec(r)[0]:"webkit":/opera/.test(r)?"opera":/msie/.test(r)?"msie":!/compatible/.test(r)&&/mozilla/.test(r)?"mozilla":"unknown",ya=(/(android|ipad|iphone|ipod|win|mac|linux)/.exec(window.navigator.platform?window.navigator.platform.toLowerCase():/android/.test(r)?"android":"unknown")||["unknown"])[0],Ca=function(){switch(Ba){case "chrome":case "safari":case "webkit":return"-webkit-";case "mozilla":return"-moz-";
case "msie":return"-ms-";case "opera":return"-o-";default:return""}}(),Da=function(){switch(Ba){case "chrome":case "safari":case "webkit":return"Webkit";case "mozilla":return"Moz";case "msie":return"ms";case "opera":return"O";default:return""}}();function Ea(a,b,c){var d=document.documentElement.style,b=b&&Da?Da+a.charAt(0).toUpperCase()+a.substr(1):!1;return!c&&typeof d[a]!=="undefined"||!!b&&typeof d[b]!=="undefined"}
var Fa="orientation"in window,Ga="createTouch"in document||/android/.test(r),Ha=function(){if(window.navigator.plugins&&window.navigator.plugins.length)return!!window.navigator.plugins["Shockwave Flash"];else if("ActiveXObject"in window)try{return!!new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(a){}return!1}(),Ia=va?!1:"CSSFontFaceRule"in window?!0:Ba==="msie"?!0:!1,Ja="getContext"in document.createElement("canvas");
if("createElementNS"in document)var Ka="createElementNS"in document&&"createSVGRect"in document.createElementNS("http://www.w3.org/2000/svg","svg"),La=Ka&&/SVG/.test(document.createElementNS("http://www.w3.org/2000/svg","animate").toString()),Ma=Ka&&/SVG/.test(document.createElementNS("http://www.w3.org/2000/svg","clipPath").toString());var Na,Oa=document.createElement("div");Oa.innerHTML="<svg/>";Na=(Oa.firstChild&&Oa.firstChild.namespaceURI)=="http://www.w3.org/2000/svg";
var Pa="canPlayType"in document.createElement("video"),Qa="localStorage"in window&&!va,Sa="applicationCache"in window,Ta=window.navigator.standalone,Ua=Ea("transformProperty")||Ea("transform",!0,!0),Va=Ea("perspectiveProperty")||Ea("perspective",!0,!0);
if(Va&&"WebkitPerspective"in document.documentElement.style&&Ba!=="safari"){var Wa=document.createElement("style"),Xa=document.createElement("div"),Ya="@media (perspective)",Za;Ya+=",("+Ca+"perspective)";Wa.textContent=Ya+"{#ts-test {height:3px}}";Xa.setAttribute("id","ts-test");document.documentElement.appendChild(Wa);document.documentElement.appendChild(Xa);Za=Xa.offsetHeight===3;document.documentElement.removeChild(Wa);document.documentElement.removeChild(Xa);Va=Za}
var $a=Va,ab=Ea("transitionProperty",!0);function s(a){return a?"":"no-"}var bb=!1;
function cb(){ta||(ta=[],ta.push("js",s(Ja)+"canvas",s(Qa)+"localstorage",s(Pa)+"video",s(Sa)+"applicationcache",s(Ia)+"fontface",s(Ga)+"touch",s(Ua)+"csstransforms",s($a)+"csstransforms3d",s(ab)+"csstransitions",s(Ka)+"svg",s(Na)+"inlinesvg",s(La)+"smil",s(Ma)+"svgclippaths",s(wa)+"treesaver",s(Ha)+"flash",s(Fa)+"orientation",s(Ta)+"fullscreen",s(va)+"legacy",s(za)+"mobile",s(Aa)+"smallscreen",s(t.qc())+"cached",s(!1)+"nativeapp","browser-"+Ba,"os-"+ya));ua=[s(!t.ob())+"offline"];Fa&&ua.push("orientation-"+
(window.orientation?"horizontal":"vertical"));var a=document.documentElement.className;bb||(bb=!0,a=a?a.replace(/no-js|no-treesaver/g,""):"",a+=" "+ta.join(" "));a=a.replace(db,"");a+=" "+ua.join(" ");document.documentElement.className=a.split(/\s+/).join(" ")}var eb=["offline","orientation-vertical","orientation-horizontal"],db=function(){var a=eb.map(function(a){return"((no-)?"+a+")"});return RegExp(a.join("|"))}();
function fb(a,b){return!a.length?!0:a.every(function(a){var d=a.substr(0,3)==="no-",a=d?a.substr(3):a,e=ta.concat(b?ua:[]);return d?e.indexOf(a)===-1:e.indexOf(a)!==-1?!0:!b&&eb.indexOf(a)!==-1?!0:!1})};function w(a,b){a.className?y(a,b)||(a.className+=" "+b):a.className=b;if(va)a.className=a.className}function gb(a,b){a.className=a.className.replace(RegExp("(^|\\s)"+b+"(\\s|$)"),"$2")}function y(a,b){return!(!a.className||!RegExp("(^|\\s)"+b+"(\\s|$)").test(a.className))}
function A(a,b){b||(b=document);var c=[];if("querySelectorAll"in b)c=q(b.querySelectorAll("."+a));else{var d=RegExp("(^|\\s)"+a+"(\\s|$)");q(b.getElementsByTagName("*")).forEach(function(a){d.test(a.className)&&c.push(a)})}return c}function hb(a,b){b||(b=document);return q(b.getElementsByTagName(a))}
function ib(a,b,c,d){d||(d=document);c=c||"*";if("querySelectorAll"in d)return q(d.querySelectorAll(c+"["+a+(b?'~="'+b+'"':"")+"]"));else{var e=[],c=hb(c,d),g=b?RegExp("(^|\\s)"+b.replace(/[.*+?\^${}()|\[\]\/\\]/g,"\\$&")+"(\\s|$)"):{test:function(){return!0}},a=a==="class"?"className":a;c.forEach(function(b){jb(b,a)&&g.test(b.getAttribute(a))&&e.push(b)});return e}}function jb(a,b){return"hasAttribute"in a?a.hasAttribute(b):b==="className"?a.className!=="":a.getAttribute(b)!==j}
function kb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function lb(a){if("outerHTML"in a)return a.outerHTML;var a=a.cloneNode(!0),b;mb.appendChild(a);b=mb.innerHTML;mb.removeChild(a);return b}function nb(a){document.body.appendChild(mb);mb.innerHTML=a;a=mb.firstChild;kb(mb);document.body.removeChild(mb);return!a||a.nodeType!==1?j:a}if("Node"in window&&Node.prototype&&!Node.prototype.contains)Node.prototype.contains=function(a){return!!(this.compareDocumentPosition(a)&16)};var mb=document.createElement("div");
mb.style.display="none";function qb(a,b){"insertRule"in rb?rb.insertRule(a+"{"+b+"}",0):rb.addRule(a,b)}var rb=document.createElement("style");rb.setAttribute("type","text/css");hb("head").length&&(hb("head")[0].appendChild(rb),rb=document.styleSheets[document.styleSheets.length-1],qb(".offscreen","position:absolute;top:-200%;right:-200%;visibility:hidden;"),qb(".grid","top:50%"),ab&&$a&&(qb(".grid, .scroll-container","backface-visibility:hidden"),Ca&&qb(".grid, .scroll-container",Ca+"backface-visibility:hidden")));function sb(a){return document.defaultView.getComputedStyle(a,j)}if(!document.defaultView||!document.defaultView.getComputedStyle)sb=function(a){return a.currentStyle};var tb=/^-?\d+(?:px)?$/i,ub=/^-?\d/;function vb(a,b){if(!a)return!1;var c=a.k||a.k===0?a.k:a.b;return b.c>=(a.H||a.H===0?a.H:a.c)&&b.b>=c&&b.c<=a.Ra&&b.b<=a.V}function B(a,b){return b&&tb.test(b)?parseFloat(b)||0:j}function C(a){return a&&a.offsetHeight||0}function wb(a){return a&&a.offsetWidth||0}function xb(a){return a&&a.offsetTop||0}
if(!document.defaultView||!document.defaultView.getComputedStyle)va&&(xb=function(a){return a?(a.style.zoom=1,a.offsetTop):0},C=function(a){return a?(a.style.zoom=1,a.offsetHeight):0},wb=function(a){return a?(a.style.zoom=1,a.offsetWidth):0}),B=function(a,b){var c,d,e;if(b&&tb.test(b))return parseFloat(b);else if(b&&ub.test(b))return c=a.style.left,d=a.runtimeStyle.left,a.runtimeStyle.left=a.currentStyle.left,a.style.left=b||0,e=a.style.pixelLeft,a.style.left=c,a.runtimeStyle.left=d,e;return j};
function E(a,b,c){a.style[b]=c+"px";return c}if(Ua)var yb=function(a,b){"transformProperty"in a.style?a.style.transformProperty=b:a.style[Da+"Transform"]=b},zb=$a?function(a,b,c){yb(a,"translate3d("+b+"px,"+c+"px,0)")}:function(a,b,c){yb(a,"translate("+b+"px,"+c+"px)")},Ab=function(a,b){zb(a,b,0)};else zb=function(a,b,c){E(a,"left",b);E(a,"top",c)},Ab=function(a,b){E(a,"left",b)};function Bb(a,b){return Math.ceil(a)+b-a%b}
function F(a){if(a){var b=sb(a);a.getAttribute("style");var c;this.display=b.display;this.position=b.position;if(va)a.style.zoom=1;this.marginTop=B(a,b.marginTop)||0;this.marginBottom=B(a,b.marginBottom)||0;this.marginLeft=B(a,b.marginLeft)||0;this.marginRight=B(a,b.marginRight)||0;this.marginHeight=this.marginTop+this.marginBottom;this.marginWidth=this.marginLeft+this.marginRight;this.borderTop=B(a,b.borderTopWidth);this.borderBottom=B(a,b.borderBottomWidth);this.borderLeft=B(a,b.borderLeftWidth);
this.borderRight=B(a,b.borderRightWidth);this.paddingTop=B(a,b.paddingTop);this.paddingBottom=B(a,b.paddingBottom);this.paddingLeft=B(a,b.paddingLeft);this.paddingRight=B(a,b.paddingRight);this.D=this.borderTop+this.paddingTop;this.ka=this.borderBottom+this.paddingBottom;this.N=this.D+this.ka;this.ec=this.borderLeft+this.paddingLeft;this.fc=this.borderRight+this.paddingRight;this.Ja=this.ec+this.fc;this.sa=wb(a);this.l=C(a);this.c=this.sa-this.Ja;this.b=this.l-this.N;this.H=B(a,b.minWidth)||0;this.k=
B(a,b.minHeight)||0;c=B(a,b.maxWidth);this.Ra=!c||c===-1?Infinity:c;c=B(a,b.maxHeight);this.V=!c||c===-1?Infinity:c;this.lineHeight=B(a,b.lineHeight)||j}}F.prototype.F=function(){var a=new F,b;for(b in this)a[b]!==this[b]&&(a[b]=this[b]);return a};function G(a,b,c){var d=document.createEvent("UIEvents"),e;d.initEvent(b,!1,!0);if(c)for(e in c)d[e]=c[e];return a.dispatchEvent(d)}function H(a,b,c){a.addEventListener(b,c,!1)}function K(a,b,c){a.removeEventListener(b,c,!1)}
if(!("addEventListener"in document))var Cb="abort,activate,afterprint,afterupdate,beforeactivate,beforecopy,beforecut,beforedeactivate,beforeeditfocus,beforepaste,beforeprint,beforeunload,beforeupdate,blur,bounce,cellchange,change,click,contextmenu,controlselect,copy,cut,dataavailable,datasetchanged,datasetcomplete,dblclick,deactivate,drag,dragend,dragenter,dragleave,dragover,dragstart,drop,error,error,errorupdate,filterchange,finish,focus,focusin,focusout,hashchange,help,keydown,keypress,keyup,layoutcomplete,load,losecapture,message,mousedown,mouseenter,mouseleave,mousemove,mouseout,mouseover,mouseup,mousewheel,move,moveend,movestart,offline,online,page,paste,progress,propertychange,readystatechange,readystatechange,reset,resize,resizeend,resizestart,rowenter,rowexit,rowsdelete,rowsinserted,scroll,select,selectionchange,selectstart,start,stop,storage,storagecommit,submit,timeout,unload".split(","),Db=
function(){this.returnValue=!1},Eb=function(){this.cancelBubble=!0},G=function(a,b,c){var d=document.createEventObject(),e;d.type=b;if(c)for(e in c)d[e]=c[e];if(!d.preventDefault)d.preventDefault=Db;if(!d.stopPropagation)d.stopPropagation=Eb;try{return a.fireEvent("on"+b,d)}catch(g){}a.q&&a.q[b]&&a.q[b].sb(d);return!1},Fb=function(a,b){return function(c){c=c||window.event;c.target=c.target||c.srcElement;c.preventDefault=Db;c.stopPropagation=Eb;a.q[b].ya.forEach(function(b){try{"handleEvent"in b?b.handleEvent(c):
b.call(a,c)}catch(e){}})}},H=function(a,b,c){if(!a.q)a.q={};a.q[b]||(a.q[b]={ya:[],sb:Fb(a,b)},Cb.indexOf(b)!==-1&&a.attachEvent("on"+b,a.q[b].sb));a.q[b].ya.push(c)},K=function(a,b,c){a.q&&a.q[b]&&(c=a.q[b].ya.indexOf(c),c!==-1&&ka(a.q[b].ya,c),a.q[b].ya.length||(Cb.indexOf(b)!==-1&&a.detachEvent("on"+b,a.q[b].sb),a.q[b]=j))};da("treesaver.addListener",H);da("treesaver.removeListener",K);function Gb(a,b,c){this.$=a;this.s=b;this.g=c}var Hb=new Gb(Infinity,Infinity,Infinity);Gb.prototype.Fb=function(){return!this.$&&!this.s&&!this.g};function Ib(a,b){if(a.$!==b.$)return b.$-a.$;else if(a.g!==b.g)return a.g-b.g;return b.s-a.s}Gb.prototype.F=function(){return new this.constructor(this.$,this.s,this.g)};function Jb(){this.g=this.f=this.index=0;this.B=!1;this.t=[];this.oa=[];this.Ea=0}Jb.prototype.F=function(){var a=new this.constructor;a.index=this.index;a.f=this.f;a.g=this.g;a.B=this.B;a.t=this.t.slice(0);a.oa=this.oa.slice(0);a.Ea=this.Ea;return a};Jb.prototype.da=function(a){return!!a&&a.index===this.index&&a.f===this.f&&a.g===this.g&&a.t.length===this.t.length};
function Kb(a,b){if(a.g)return!1;var c,d,e;for(c=a.index,d=b.i.length;c<d;c+=1){e=b.i[c];if(!e.Ca)return!1;if(!Lb(a,c)&&!e.s.ha)return!1}if(!a.t.length&&a.f===b.n.length)return!0;for(c=a.t.slice(0);c.length;)if(e=b.n[c.pop()],!e.ha)return!1;for(c=a.f,d=b.n.length;c<d;c+=1)if(e=b.n[c],!e.ha)return!1;return!0}function Mb(a,b){var c;if(b<a.f)(c=a.t.indexOf(b))!==-1?ka(a.t,c):(c=a.oa.indexOf(b))!==-1&&ka(a.oa,c);else{if(b>a.f)for(;a.f<b;a.f+=1)a.t.push(a.f);a.f=b+1}}
function Nb(a,b){a.t.indexOf(b)===-1&&(Mb(a,b),a.t.push(b))}function Lb(a,b){return a.f<=b?!1:a.t.indexOf(b)!==-1?!1:a.oa.indexOf(b)!==-1?!1:!0};function Ob(a,b,c,d){this.j=a;this.H=parseInt(b||0,10);this.k=parseInt(c||0,10);this.C=d}Ob.prototype.ga=function(){return!this.C?!0:fb(this.C,!0)};function Pb(a,b,c){c&&w(b,c);b.innerHTML=a.j;["img","iframe","video"].forEach(function(a){ib("data-src",j,a,b).forEach(function(a){a.setAttribute("src",a.getAttribute("data-src"))})})};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};function Qb(a,b,c){this.Cc=c.index;this.f=c.f;c.f+=1;this.pa=j;this.o={};this.ha=!y(a,"required");this.$b=y(a,"zoomable");this.Ya=y(a,"scroll");q(a.childNodes).forEach(function(a){if(a.nodeType!==1)a.data&&a.data.trim();else{var b=a.getAttribute("data-sizes"),c=parseInt(a.getAttribute(jb(a,"width")?"width":"data-minwidth"),10),i=parseInt(a.getAttribute(jb(a,"height")?"height":"data-minheight"),10),n=jb(a,"data-requires")?a.getAttribute("data-requires").split(" "):j;if(!n||fb(n))a.removeAttribute("hidden"),
gb(a,"hidden"),a=lb(a),b=b?b.split(" "):["fallback"],Rb(this,b,a,c,i,n)}},this);this.o.fallback&&(Sb(this,this.o.fallback[0].j,a,b,c),delete this.o.fallback)}
function Sb(a,b,c,d,e){var g=c.parentNode,i=document.createElement("div");i.innerHTML=b;b=i.childNodes.length===1?i.firstChild:i;g.insertBefore(b,c);a.$b&&(w(b,"zoomable"),b.setAttribute("data-figureindex",a.f),Ga&&b.setAttribute("onclick","void(0)"));Tb(b,d);a.pa=new Ub(b,d,e,!0);a.pa.s=a;a.pa.i&&a.pa.i.forEach(function(a){a.s=this;a.Zb=!0},a);g.removeChild(b)}
function Vb(a,b){var c=-Infinity,d,e=Infinity,g,i,n=a.o;a.o.lightbox&&(n={lightbox:a.o.lightbox});for(i in n)a.o[i].forEach(function(a){if(a.ga()){var h=a.H*a.k;a.H&&a.H>b.c||a.k&&a.k>b.b?!g&&this.Ya&&h<=e&&(e=h,d={name:i,wa:a}):h>=c&&(c=h,g={name:i,wa:a})}},a);return g||d}function Rb(a,b,c,d,e,g){var i=new Ob(c,d,e,g);b.forEach(function(a){this.o[a]?this.o[a].push(i):this.o[a]=[i]},a)}function Wb(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&b==="figure"};function Ub(a,b,c,d){var e=Xb(a),g,i="";if(a.nodeType!==1)this.za=!0;else if(C(a)){this.index=c.index;c.index+=1;this.ea=!e&&Yb(a);this.ca=this.Zb=this.Ca=!1;this.s=j;this.i=[];this.n=[];g=!1;if(this.ea&&!y(a,"keeptogether"))ac(this,a,b,c,d),g=!!this.n.length,this.ea=!!this.i.length;this.bb=this.bb||!e;this.nc=y(a,"keepwithnext");this.gc=y(a,"columnbreak");this.qa=this.qa||!this.bb||y(a,"keeptogether");this.d=new F(a);if(!this.d.lineHeight)this.d.lineHeight=b;if(!this.qa)this.qa=this.d.N+this.d.lineHeight===
this.d.l;this.xa=this.qa?this.d.l:!this.ea?this.d.D+this.d.lineHeight:!this.ca?this.d.D+this.i[0].xa+(this.d.D?this.i[0].d.marginTop:0):this.d.D+this.i[0].xa;this.j=lb(a);this.Qb=this.ea?this.j.substr(0,this.j.indexOf(">")+1):j;this.cb=this.ea?this.j.slice(this.j.lastIndexOf("<")):j;if(g)this.j=this.Qb,this.i.forEach(function(a){this.j+=a.j},this),this.j+=this.cb;this.ea&&(a=a.cloneNode(!0),this.d.marginTop&&E(a,"marginTop",0),this.d.borderTop&&E(a,"borderTopWidth",0),this.d.paddingTop&&E(a,"paddingTop",
0),i=lb(a));this.sc=this.ea?i.substr(0,i.indexOf(">")+1):j}else this.za=!0}function bc(a){return a.nextSibling?a.nextSibling:a.parent?bc(a.parent):j}
function ac(a,b,c,d,e){var g,i=a instanceof Ub,n=b.nodeName.toLowerCase()==="ol"&&"start"in b,l=n?b.start:j;l===-1&&(l=1);q(b.childNodes).forEach(function(b){if(n&&b.nodeName.toLowerCase()==="li"){if(b.value&&b.value!==-1)l=b.value;b.setAttribute("value",l);l+=1}if(Wb(b)){if(e)return;b=new Qb(b,c,d);a.n.push(b);if(b=b.pa)if(b.Ca=!0,i)a.ca=!0}else if(b=new Ub(b,c,d,!!e),i&&!a.ca)a.ca=b.ca;if(b&&!b.za){a.i=a.i.concat(b,b.i||[]);if(b.n.length)a.n=a.n.concat(b.n),delete b.n;b.parent=i?a:j;if(g)g.nextSibling=
b;g=b}})}function cc(a){for(var a=a.parent,b=[];a;)b.unshift(a.sc),a=a.parent;return b.join("")}function dc(a){for(var a=a.parent,b=[];a;)b.push(a.cb),a=a.parent;return b.join("")}
function Yb(a){if(ec(a))return!1;if(fc(a))return!0;var b,c,d,e=!1;for(b=0,c=a.childNodes.length;b<c;b+=1)if(d=a.childNodes[b],d.nodeType===3&&/[^\s]/.test(d.data))return!1;else if(d.nodeType===1){if(ec(d)||fc(d))return!0;e=!0;d=sb(d);if(/inline/.test(d.display))return!1;else if(/block/.test(d.display))return!0}return e}var gc="img,video,object,embed,iframe,audio,canvas,svg,table".split(",");function Xb(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&gc.indexOf(b)!==-1}var hc="p,h1,h2,h3,h4,h5,h6".split(",");
function ec(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&hc.indexOf(b)!==-1}var ic="div,article,ul,ol,figure,aside".split(",");function fc(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&ic.indexOf(b)!==-1}
function Tb(a,b){if(a.nodeType===1){var c,d;a.removeAttribute("id");if(!Wb(a)){if(Yb(a)&&!y(a,"keeptogether"))for(c=a.childNodes.length-1;c>=0;c-=1)d=a.childNodes[c],d.nodeType!==1?a.removeChild(d):Tb(d,b);if(!window.TS_NO_AUTOMETRICS)if(c=new F(a),c.marginTop%b&&E(a,"marginTop",Bb(c.marginTop,b)),c.marginBottom%b&&E(a,"marginBottom",Bb(c.marginBottom,b)),Xb(a)||y(a,"keeptogether"))c.l%b&&E(a,"paddingBottom",c.paddingBottom+b-c.l%b);else{c.lineHeight?c.lineHeight%b&&E(a,"lineHeight",Bb(c.lineHeight,
b)):(c.lineHeight=b,E(a,"lineHeight",b));c.D%b&&E(a,"paddingTop",Bb(c.D,b)-c.borderTop);if(c.ka%b)c.paddingBottom=E(a,"paddingBottom",Bb(c.ka,b)-c.borderBottom);c.l=C(a);c.l%b&&(c.paddingBottom+=b-c.l%b,E(a,"paddingBottom",c.paddingBottom))}}}};function jc(a,b){this.lineHeight=B(a,sb(a).lineHeight)||1;this.ba=a.offsetWidth;hb("figure",a).forEach(function(a){a.style.display="none"});Tb(a,this.lineHeight);this.n=[];this.i=[];this.ib=b;ac(this,a,this.lineHeight,{index:0,f:0})};function kc(a,b){var c=new F(a);this.w=!y(a,"fixed");(this.k=c.k)&&E(a,"minHeight",0);this.b=c.l;this.Ma=Math.max(0,b-this.b)}kc.prototype.Ga=function(a){if(!this.w)return this;this.b=Math.max(0,a-this.Ma);return this};function lc(a,b){var c=new F(a);this.w=!y(a,"fixed");(this.k=c.k)&&E(a,"minHeight",0);this.b=c.l;this.Ma=Math.max(0,b-this.b);this.o=(c=a.getAttribute("data-sizes"))?c.split(" "):[]}lc.prototype.Ga=function(a){if(!this.w)return this;this.b=Math.max(0,a-this.Ma);return this};function mc(a){document.body.appendChild(a);this.C=jb(a,"data-requires")?a.getAttribute("data-requires").split(" "):j;this.Ib=!a.className?[]:a.className.toLowerCase().split(/\s+/);this.w=!y(a,"fixed");nc(this);this.Ha=this.size=new F(a);this.w?this.size.H=Math.max(this.size.H||0,this.size.c):(this.size.k=this.size.b,this.size.H=this.size.c);this.lineHeight=this.size.lineHeight||1;this.ba=this.fa=this.Z=0;this.error=!1;this.cols=[];A("column",a).forEach(function(a){var c=new kc(a,this.size.b);this.cols.push(c);
this.Z+=c.b;this.fa=Math.max(this.fa,c.b);if(this.ba){if(this.ba!==a.offsetWidth)this.error=!0}else this.ba=a.offsetWidth},this);this.G=[];A("container",a).forEach(function(a){this.G.push(new lc(a,this.size.b))},this);this.j=lb(a);document.body.removeChild(a)}var oc={onlypage:!0,odd:!0,even:!0,sizetocontainer:!0},pc=/^(no-)?page-(\d+)$/;
function nc(a){var b=!1,c,d;a.K={};a.Ta={};a.Rb={};a.Ib.forEach(function(a){if(a in oc)this.K[a]=!0;else if(c=pc.exec(a))d=parseInt(c[2],10),isNaN(d)||(a.substr(0,3)==="no-"?this.Rb[d]=!0:(b=!0,this.Ta[d]=!0))},a);if(!b)a.Ta=j}
mc.prototype.Ga=function(a){if(!this.w)return this;var b=Math.min(this.size.V,Math.max(a-(this.size.marginHeight+this.size.N),this.size.k));b-=(b-this.size.k||0)%this.lineHeight;this.Z=this.fa=0;this.cols.forEach(function(a){this.Z+=a.Ga(b).b;this.fa=Math.max(this.fa,a.b)},this);this.G.forEach(function(a){a.Ga(b)},this);this.Ha=this.size.F();this.Ha.b=b;this.Ha.l=b+this.size.N;this.Ha.V=this.K.sizetocontainer?this.size.V:Math.min(this.size.V,b+this.lineHeight*3);return this};
function qc(a,b){return b.size.c+20*b.G.length-(a.size.c+20*a.G.length)}
function rc(a,b,c){var d=j,e=-Infinity,g,i,n=a.i.length,l,h,u,v,m,o,z,I,x,J,D,P,$;u=0;v=b.length;for(;u<v;u+=1){m=b[u];P=0;$=!1;g=c.F();z=g.g;I=m.Z-z;z&&m.Z&&($=!0);o=0;i=g.Ea+1;o+=m.cols.length*50;m.lineHeight!==a.lineHeight&&(o-=2E3);m.ba&&m.ba!==a.ba&&(o-=Infinity);m.K.onlypage&&(o+=g.Ea?-Infinity:4E3);m.Ta&&(m.Ta[i]?o+=3E3:o-=Infinity);m.Rb[i]&&(o-=Infinity);o+=i%2?m.K.odd?2E3:m.K.even?-Infinity:0:m.K.even?2E3:m.K.odd?-Infinity:0;i=m;l=a;h=g;var k=D=J=x=f,aa=f,Q=f,ba=f,Zb=f,V=f,ob=f,dd=f,$b=[];
x=0;J=i.G.length;for(;x<J;x+=1){D=i.G[x];$b[x]=j;Q=h.f;ob=h.t.slice(0);c:for(;ob.length||Q<l.n.length;){ba=(dd=!!ob.length)?ob.shift():Q;Zb=l.n[ba];k=D.o.length-1;d:for(;k>=0;k-=1){aa=D.o[k];e:{var V=Zb,pb=aa,Ra=f,ed=f;if(V.o[pb])for(Ra=0,ed=V.o[pb].length;Ra<ed;Ra+=1)if(V.o[pb][Ra].ga()){V=V.o[pb][Ra];break e}V=j}if(V){if(D.w&&V.k&&V.k>D.b)continue d;$b[x]={f:ba,wa:V,size:aa,w:D.w};Mb(h,ba);break c}}if(!Zb.ha)break;dd||(Q+=1)}}i=$b;h=0;x=i.length;for(;h<x;h+=1)J=m.G[h],(D=i[h])?(l=a.n[D.f],o+=2E3+
D.wa.k*5,l.ha||(o+=4E3),J.w||(o+=5E3),P+=1):J.w||(o-=5E3);b:for(;m.Z&&g.index<n&&z<=m.Z;){l=a.i[g.index];h=l.d.l+l.d.marginTop;if(l.qa&&(h>m.fa||h>I))break b;if(h>I){if(l.qa)break b;if(l.children){g.index+=1;continue b}z+=h}z+=h;o+=h;I-=h;$=!0;g.index=l.nextSibling?l.nextSibling.index:g.index+1}if($)I>0&&(g=I/m.Z,g-=P*0.2,g>0.5&&(o-=I,o-=g*g*2E3));else if(P){if((l=a.i[g.index])&&l.s&&!l.s.ha&&(g.g||l.Zb))o=-Infinity}else o=-Infinity;o>e&&(e=o,d={P:m,G:i})}return d};function sc(a){this.a=a;this.Ka=a.firstChild}function tc(a){a.Bb={c:wb(a.a),b:C(a.a)};a.eb={c:wb(a.Ka),b:C(a.Ka)};a.Lb=a.eb.c>a.Bb.c;a.yb=a.yb||0;a.zb=a.zb||0;uc(a,0,0,!0)}sc.prototype.contains=function(a){return this.Ka.contains(a)};function uc(a,b,c,d){b=Math.max(0,Math.min(a.eb.c-a.Bb.c,a.yb+b));c=Math.max(0,Math.min(a.eb.b-a.Bb.b,a.zb+c));if(d)a.yb=b,a.zb=c;zb(a.Ka,-b,-c)}
function vc(a){var b=document.createElement("div");w(b,"scroll-container");for(Ga&&a.setAttribute("onclick","void(0)");a.firstChild;)b.appendChild(a.firstChild);a.appendChild(b)};function wc(a,b,c){var d=rc(a,b,c),b=document.createElement("div"),e=c.F(),g=!1;!d||!d.P?(c.B=Kb(c,a)||c.f===a.n.length,c.B?this.za=!0:this.error=!0):(this.size=d.P.Ha.F(),this.Gb=new Gb(c.index,c.f,c.g),w(b,"offscreen"),document.body.appendChild(b),b.innerHTML=d.P.j,this.a=b.firstChild,E(this.a,"width",this.size.c),E(this.a,"height",this.size.b),ib("data-template","document",j,this.a).forEach(function(b){b.innerHTML=Mustache.to_html(b.innerHTML,a.ib.u)}),A("container",this.a).forEach(function(b,
e){var l=d.G[e],h,u,v;if(l){u=l.f;h=a.n[u];a:{var m=a.lineHeight,o,z,I;v=!0;o=l.size;z=l.wa;I=C(b);Pb(z,b,o);if(l.w){y(b,"bottom")?(v=!1,b.style.top="auto"):b.style.bottom="auto";z=new F(b);l=z.l;if(l>I)if(h.Ya)l=I,E(b,"height",l-z.N);else{gb(b,o);kb(b);v=!1;break a}else m&&l%m&&(l=Bb(l,m));h.Ya&&(w(b,"scroll"),vc(b));for(m=b;m=m.nextSibling;)if(m.nodeType===1&&!y(m,"fixed")&&(y(m,"column")||y(m,"container")||y(m,"group")))w(m,"flexed"),C(m)<=l?E(m,"height",0):v?E(m,"top",xb(m)+l):E(m,"bottom",C(m.offsetParent)-
(xb(m)+C(m))+l)}v=!0}if(v){if(Mb(c,u),g=!0,h.$b&&(w(b,"zoomable"),b.setAttribute("data-figureindex",u),Ga&&b.setAttribute("onclick","void(0)")),e===0&&d.P.K.sizetocontainer)this.size.b=C(b)+d.P.G[0].Ma,this.size.l=this.size.b+this.size.N,E(this.a,"height",this.size.b)}else!h.ha&&h.pa?Nb(c,h.f):y(b,"flexed")||(Mb(c,u),c.oa.push(u)),b.parentNode.removeChild(b)}else b.parentNode.removeChild(b)},this),A("column",this.a).forEach(function(b,e){var g=d.P.fa,h=d.P.cols[e].k,u=C(b),v=0,m,o,z=!0,I=0,x=0,J=
0,D=0,P=[],$=a.i.length,k=a.i[c.index],aa,Q,x=[],ba,x=!1,g=g/u>1.5;if(k&&(u%a.lineHeight&&(u-=u%a.lineHeight),u&&!(u<h))){k.parent&&P.push(cc(k));I=c.g?k.d.l-c.g:0;a:for(;c.index<$&&v<u;){k=a.i[c.index];Q=(aa=k.nextSibling)||bc(k);if(k.Ca&&Lb(c,k.s.f)&&(!z||!c.g)){c.index=Q?Q.index:$;continue a}h=k.parent;m=u-v;z&&!J?(J=-I,x=c.overflow?k.d.lineHeight:k.xa):(J=Math.max(J,k.d.marginTop),x=J+k.xa);D=Math.max(k.d.marginBottom,aa?aa.d.marginTop:0);ba=k.d.l+J;x=m<x;if(!x&&k.nc&&aa&&!(c.g||z&&!g))x=m>=ba&&
m<ba+D+aa.xa;x&&(x=!z||g);x&&(x=!k.ca);k.gc&&!z&&(x=!0);if(x){if(h){for(;h&&h.index===k.index-1;)P.pop(),c.index=h.index,h.Ca&&Nb(c,h.s.f),k=h,h=k.parent;h&&P.push(dc(k))}break a}k.Ca&&Mb(c,k.s.f);if(k.ca||k.i.length&&m<ba){k.d.D&&(v+=z?0:J,J=0,v+=k.d.D);P.push(k.Qb);c.index+=1;continue a}v+=ba;P.push(k.j);z=!1;o=o||k;c.g=0;if(u>v+D){c.index=Q?Q.index:$;if(!aa&&h){x=[];do x.push(h.cb),h.d.ka?(v+=D+h.d.ka,D=h.d.marginBottom):D=Math.max(D,h.d.marginBottom);while(!h.nextSibling&&(h=h.parent));if(u>v+
D)P.push(x.join(""));else{h&&P.push(dc(k));v=u;break a}}J=D;continue a}h&&P.push(dc(k));if(k.bb){if(v<=u)c.index=Q?Q.index:$,v=u}else v=u,c.index=Q?Q.index:$;break a}z=k;if(u>=v||!z)c.g=0;else if(c.g=v-u,v=c.g-z.d.ka,v<=0)c.g=0,c.index=z.index+1;else if(v=(z.d.b-v)%z.d.lineHeight)u-=v,c.g+=v;E(b,"height",u);b.innerHTML=P.join("");if(o&&b.firstChild)if(b.firstChild.style.marginTop=-I+"px",o.parent&&!I){for(h=o.parent;h;)h.d.D&&(o=h),h=h.parent;if(h!==o){h=o.parent;for(k=b.firstChild;h;)k=k.firstChild,
h=h.parent,k&&(k.style.marginTop=0)}}else{if(o.i.length&&!I)for(k=b.firstChild;o;)o.i.length&&k.firstChild?(o=o.i[0],k=k.firstChild,k.style.marginTop=0):o=j}else kb(b)}}),e.da(c)?this.error=!0:!g&&d.P.K.sizetocontainer?this.za=!0:(E(this.a,"marginTop",-this.size.l/2),c.B=d.P.K.onlypage||Kb(c,a),c.B&&w(this.a,"last-page"),this.j=b.innerHTML,this.end=new Gb(c.index,c.f,c.g),this.p=!1,c.Ea+=1),b.removeChild(this.a),this.a=j,document.body.removeChild(b),b=j)}
wc.prototype.M=function(){if(this.p)return this.a;this.a=nb(this.j);this.X=A("scroll",this.a).map(function(a){return new sc(a)});this.p=!0;return this.a};wc.prototype.A=function(){this.p=!1;this.a=this.X=j};wc.prototype.F=function(){var a=Object.F(this);a.a=this.a&&this.a.cloneNode(!0)||j;a.p=this.p;return a};var t={ac:1E4,na:{cc:"treesaver.online",bc:"treesaver.offline"},Yb:["offline","online"],Xb:"uncached,idle,checking,downloading,updateready,obsolete".split(","),Qa:!1};t.load=function(){if(!t.Qa)t.Qa=!0,t.Yb.forEach(function(a){H(document,a,t)}),Sa&&t.rb&&t.Xb.forEach(function(a){H(window.applicationCache,a,t)})};t.Bc=function(){if(t.Qa)t.Qa=!1,t.Yb.forEach(function(a){K(window,a,t)}),Sa&&t.rb&&t.Xb.forEach(function(a){K(window.applicationCache,a,t)})};
t.ob=function(){return"onLine"in window.navigator?window.navigator.onLine:!0};t.rb=Sa&&!!window.applicationCache.status;t.qc=function(){return t.rb};t.handleEvent=function(a){switch(a.type){case "online":cb();G(window,t.na.cc);break;case "offline":cb();G(window,t.na.bc);break;case "updateready":window.applicationCache.swapCache()}};t.uc=/^https?:\/\//i;
t.Ia=function(a){if(a&&a.charAt(0)==="/"||t.uc.test(a))return a;var b=document.createElement("a"),c;va&&(c=document.createElement("div"),document.body.appendChild(c),c.appendChild(b));b.href=a;a=b.href;va&&(document.body.removeChild(c),c.removeChild(b));return a};t.get=function(a,b,c){var d={L:new XMLHttpRequest,url:a,Hb:b};na(function(){t.wc(d)},c||t.ac,[],t.Pb(d));d.L.onreadystatechange=t.hc(d);try{d.L.open("GET",d.url,!0),d.L.send(j)}catch(e){t.xb(d)}};t.Pb=function(a){return"fetch:"+a.url};
t.hc=function(a){return function(){a.L.readyState===4&&(a.L.status===0||a.L.status===200||a.L.status===304?(a.Hb(a.L.responseText,a.url),t.Jb(a)):t.xb(a))}};t.Jb=function(a){sa(t.Pb(a));a.L.onreadystatechange=j};t.xb=function(a){a.Hb(j,a.url);t.Jb(a)};t.wc=function(a){a.L.abort();t.xb(a)};var xc=/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,yc="source,scheme,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(",");function zc(a){for(var b=yc.length,a=xc.exec(a),c={};b--;)c[yc[b]]=a[b]||j;return c}
function Ac(a){var b="";a.scheme&&(b+=a.scheme+":");a.source&&/^(?:[^:\/?#]+:)?\/\//.test(a.source)&&(b+="//");a.authority&&(a.userInfo&&(b+=a.user||"",a.userInfo.indexOf(":")!==-1&&(b+=":"),b+=a.password||"",b+="@"),b+=a.host||"",a.port!==j&&(b+=":"+a.port));a.relative&&(a.path&&(b+=a.directory||"",b+=a.file||""),a.query&&(b+="?"+a.query),a.anchor&&(b+="#"+a.anchor));return b}
function Bc(a){return/(index|default)\.(html?|php|asp|aspx)$/i.test(a)||Cc.DirectoryIndex&&a.lastIndexOf(Cc.DirectoryIndex)===a.length-Cc.DirectoryIndex.length}function Dc(a){a=zc(a);a.anchor=j;return Ac(a)}function Ec(a){a=zc(a);a.file=j;return Ac(a)};function Fc(a,b,c){this.aa=this.content=this.ta=j;this.v=0;this.h=[];this.error=this.qb=this.U=this.loaded=this.J=this.Fa=!1;this.ma=this.ra=j;this.lb=[];this.mb=a;this.ib=c;if(b)if(b.nodeName!=="ARTICLE")this.error=!0;else{this.loaded=!0;a=document.createElement("div");c=document.createElement("div");a.style.display="none";w(a,"offscreen grid");w(c,"column");document.body.appendChild(a);b.removeAttribute("id");kb(a);if(this.ta=b.getAttribute("data-theme")||b.getAttribute("data-grids")||j)w(a,this.ta),
w(c,this.ta),Gc(this,this.mb);for(;b.firstChild;)c.appendChild(b.firstChild);a.appendChild(c);c.style.display="block";a.style.display="block";this.content=new jc(c,this.ib);document.body.removeChild(a);a.removeChild(c);kb(c);Hc(this)}}function Gc(a,b){a.mb=a.ta?b.filter(function(a){return a.Ib.indexOf(this.ta)!==-1},a):b.slice(0)}
function Ic(a,b){a.lb=a.mb.filter(function(a){return(!a.C?!0:fb(a.C,!0))&&vb(a.size,{c:b.c-a.size.Ja,b:b.b-a.size.N-a.size.marginHeight})}).map(function(a){return a.Ga(b.b)});a.lb.sort(qc)}function Jc(a,b){if(!a.ra||a.ra.c!==b.c||a.ra.b!==b.b)a.ra=b,a.Fa=vb(a.ma,b);return!a.Fa}function Hc(a){sa("paginate");a.h=[];a.v=0;a.ra&&Ic(a,a.ra);a.aa=new Jb;a.ma=j;a.Fa=!0;a.J=!1}
Fc.prototype.tc=function(a,b,c){sa("paginate");for(var d,b=b||0;!this.aa.B;)if(d=new wc(this.content,this.lb,this.aa),d.za){if(this.aa.B)break}else{if(d.error){if(this.aa.B)break;this.error=!0;G(document,"treesaver.paginationerror",{Eb:this});this.aa.B=!0;break}this.h.push(d);this.v+=1;this.error=!1;var e=this.ma||{},g=d.size||{},i=g.N||(g.l?g.l-g.b:0),n=g.Ja||(g.sa?g.sa-g.c:0);this.ma={c:Math.max(e.c||0,g.c+n||0),b:Math.max(e.b||0,g.b+i||0),Ra:Math.min(e.Ra||Infinity,g.Ra+n||Infinity),V:Math.min(e.V||
Infinity,g.V+i||Infinity)};if(!(b&&this.v<=b||c&&(c===Hb||!(Ib(c,d.end)>=0)))&&!this.aa.B){a&&(G(document,"treesaver.paginationprogress",{Eb:this}),Kc(this,q(arguments)));return}}this.J=!0;G(document,"treesaver.paginationprogress",{Eb:this,Dc:!0})};function Kc(a,b){na(Fc.prototype.tc,200,b,"paginate",a)}
function Lc(a,b,c){a.Fa||Hc(a);var d=[],e=b>=0?b+c-1:Infinity;!a.J&&e>a.h.length-1&&Kc(a,[!0,e]);if(a.J)c=Math.min(c,a.v-(b>=0?b:b-1));else if(d.length=c,b<0)return d;if(b<0)for(e=-b;e<=c;e+=1)d[e+b]=a.h[a.v-e];else for(e=b;e<b+c;e+=1)d[e-b]=a.h[e];return d}
function Mc(){var a=L.e[M.index],b=N;if(!a.content)return-1;var c,d;if(!b||b.Fb())return 0;a.Fa||Hc(a);if(!a.J&&(b===Hb||!a.v||!(Ib(b,a.h[a.v-1].end)>=0)))return Kc(a,[!0,j,b]),-1;if(b===Hb)return a.J?a.v-1:-1;for(c=0,d=a.v;c<d;c+=1)if(Ib(a.h[c].end,b)<0)return c;return a.J?a.v-1:-1};var Nc,Oc,Pc,Qc=/<body>\s*([\s\S]+?)\s*<\/body>/i;function Rc(a){return(a=Qc.exec(a))&&a[1]?a[1]:j}function Sc(a){Pc=document.createElement("div");if(a&&(a=Rc(a))){var b=document.createElement("div");b.style.display="none";document.documentElement.appendChild(b);b.innerHTML=a;q(b.childNodes).forEach(function(a){a.nodeType===1&&a.nodeName.toLowerCase()==="div"&&Pc.appendChild(a)});document.documentElement.removeChild(b);b.innerHTML=""}Tc()}
function Tc(){Nc=Uc;var a=Oc.slice(0);Oc=[];a.forEach(function(a){a()})}function Vc(a){return Pc?A(a,Pc):[]}var Uc=2;function Wc(a){return window.JSON.parse(a)}function Xc(a){return window.JSON.stringify(a)}"JSON"in window||(Wc=function(a){try{return eval("("+a+")")}catch(b){}return j},Xc=function(){return""});function Yc(a,b,c){c=c?window.localStorage:window.sessionStorage;c.getItem(a)&&c.removeItem(a);try{c.setItem(a,Xc(b))}catch(d){}}function Zc(a){return(a=window.sessionStorage.getItem(a)||window.localStorage.getItem(a))?Wc(a):j}if(!Qa)var $c={},Yc=function(a,b){$c[a]=b},Zc=function(a){return $c[a]};function O(a,b){this.index=a;this.anchor=b}var ad=new O(Infinity),bd=new O(0);O.prototype.Fb=function(){return this.index===0};O.prototype.da=function(a){return this.index===a.index};function cd(){this.children=[];this.parent=j}cd.prototype.appendChild=function(a){a.parent=this;this.children.push(a);return a};cd.prototype.replaceChild=function(a,b){var c=this.children.indexOf(b);return c!==-1?(a.parent=b.parent,b.parent=j,this.children.splice(c,1,a)[0]):j};cd.prototype.insertBefore=function(a,b){var c=this.children.indexOf(b);a.parent=this;c===0?this.children.unshift(a):c>1&&this.children.splice(c,0,a);return a};
cd.prototype.removeChild=function(a){var a=this.children.indexOf(a),b=j;if(a!==-1)b=this.children.splice(a,1)[0],b.parent=j;return b};function R(a,b){if(a)this.url=a,this.path=zc(a).relative,this.u=b||{},this.e=[],this.ab={},this.Cb=[],this.error=this.qb=this.U=this.loaded=!1,this.children=[],this.title=j}var fd=/<title>\s*(.+?)\s*<\/title>/i;R.prototype=new cd;
R.prototype.parse=function(a){var b=document.createElement("div"),c=[];if(!a||typeof a!=="string"||a.trim()==="")return[];b.innerHTML=a;c=hb("article",b).filter(function(a){a:{for(;(a=a.parentNode)!==j&&a.nodeType===1;)if(a.nodeName==="ARTICLE")break a;a=j}return a===j});if(c.length===0)c.push(document.createElement("article")),c[0].innerHTML=b.innerHTML;return c.map(function(a,b){var c=a.getAttribute("id")||(b===0?j:"_"+b),i=new Fc(gd,a,this);c&&(this.ab[c]=b,this.Cb[b]=c);return i},this)};
R.prototype.da=function(a){var b=a;if(!b)return!1;if(typeof a!=="string"&&a.url)b=a.url;return Bc(b)&&Bc(this.url)?b===this.url:Bc(b)?Ec(b)===this.url:Bc(this.url)?b===Ec(this.url):b===this.url};R.prototype.xc=function(a){this.e=a};R.prototype.lc=function(){return this.u};function hd(a){return(a=fd.exec(a))&&a[1]?a[1]:j}
R.prototype.load=function(){var a=this,b=j;if(!this.U){this.U=!0;if(b=Zc("cache:"+this.url))this.e=this.parse(b),this.title=hd(b),this.loaded=!0,G(document,"treesaver.loaded",{document:this});t.get(this.url,function(c){a.U=!1;if(c){if(b!==c)Yc("cache:"+a.url,c,!0),a.e=a.parse(c),a.title=hd(c),a.loaded=!0,G(document,"treesaver.loaded",{document:a})}else if(!b)a.qb=!0,a.loaded=!1,G(document,"treesaver.loadfailed",{document:a})})}};da("treesaver.Document",R);
da("treesaver.Document.prototype.setArticles",R.prototype.xc);da("treesaver.Document.prototype.parse",R.prototype.parse);da("treesaver.Document.prototype.getMeta",R.prototype.lc);if(!Object.keys)Object.keys=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b};Object.F=function(a){function b(){}b.prototype=a;return new b};function id(a){this.url=a;this.children=[];this.U=this.loaded=!1;this.Na={};this.Oa={};this.T=[]}id.prototype=new cd;function jd(a,b){var c=b.url,d=b.children,e={},g=j;if(!c)return j;c=Dc(t.Ia(c));Object.keys(b).forEach(function(a){e[a]=b[a]});g=new R(c,e);d&&Array.isArray(d)&&d.forEach(function(a){g.appendChild(jd(this,a))},a);return g}
id.prototype.update=function(){var a=0;this.T=[];this.Na={};this.Oa={};kd(this,this.children,function(b){this.Na[b.url]?this.Na[b.url].push(b):this.Na[b.url]=[b];this.T.push(b);this.Oa[b.url]?this.Oa[b.url].push(a):this.Oa[b.url]=[a];a+=1},this);G(document,"treesaver.index.updated",{index:this})};function kd(a,b,c,d){return b.every(function(a){return c.call(d,a)!==!1&&kd(this,a.children,c,d)},a)}function ld(a,b){var c=-1,d=0;kd(a,a.children,function(a){a.da(b)&&(c=d);d+=1},a);return c}
id.prototype.get=function(a){var b=[];kd(this,this.children,function(c){c.da(a)&&b.push(c)},this);return b};id.prototype.parse=function(a){if(!a)return[];if(typeof a==="string")try{a=Wc(a)}catch(b){return[]}return!Array.isArray(a)?[]:a.map(function(a){return this.appendChild(jd(this,a))},this)};
id.prototype.load=function(){var a=this,b=j;if(!this.U)if(this.url){this.U=!0;if(b=Zc("cache:"+this.url))this.children=this.parse(b),this.loaded=!0,G(document,"treesaver.index.loaded",{index:this}),this.update();t.get(this.url,function(c){a.U=!1;if(c){if(b!==c)Yc("cache:"+a.url,c,!0),a.children=a.parse(c),a.loaded=!0,G(document,"treesaver.index.loaded",{index:a}),a.update()}else if(!b)a.qb=!0,a.loaded=!1,G(document,"treesaver.index.loadfailed",{index:a})})}else G(document,"treesaver.index.loadfailed",
{index:this})};var gd,S,T,M,L,N,md,nd,U,W,od,pd,qd,rd;function sd(){var a=td;T=S=-1;M=bd;gd=ud();if(!gd)return!1;U=new R(Dc(document.location.href),{});if(a)U.e=U.parse(a),U.title=document.title,U.loaded=!0;H(document,"treesaver.index.loaded",vd);W=new id(wd());W.appendChild(U);W.update();W.load();xd(U,bd,j,j,!0);yd();zd();Ad.forEach(function(a){H(document,a,Bd)});window.onpopstate=Cd;return!0}
function Dd(){N=L=j;T=S=-1;pd=od=M=j;K(document,"treesaver.index.loaded",vd);Ad.forEach(function(a){K(document,a,Bd)});window.onpopstate=j}function vd(a){var a=a.index,b=a.get(U.url);if(b.length)b.forEach(function(a){U.u=a.u;U.children=a.children;a.parent.replaceChild(U,a)}),T=ld(a,U),document.title=U.u.title||U.title}function ud(){var a=[];Vc("grid").forEach(function(b){var c=b.getAttribute("data-requires");if(!c||fb(c.split(" ")))b=new mc(b),b.error||a.push(b)});return a}
function yd(){var a=Vc("loading")[0];a||(a=document.createElement("div"));document.body.appendChild(a);a.style.top="50%";E(a,"margin-top",-C(a)/2);document.body.removeChild(a);od=lb(a);a=a.cloneNode(!0);document.body.appendChild(a);pd=new F(a);document.body.removeChild(a)}
function zd(){var a=Vc("error")[0];a||(a=document.createElement("div"));document.body.appendChild(a);a.style.top="50%";E(a,"margin-top",C(a)/2);document.body.removeChild(a);qd=lb(a);a=a.cloneNode(!0);document.body.appendChild(a);rd=new F(a);document.body.removeChild(a)}var Ad=["treesaver.loaded","treesaver.loadfailed","treesaver.paginationprogress"];
function Bd(a){if(a.type==="treesaver.paginationprogress")G(document,"treesaver.pageschanged");else if(a.type==="treesaver.loaded")document.title=L.u.title||L.title,G(document,"treesaver.pageschanged");else if(a.type==="treesaver.loadfailed"&&a.document===L)t.ob()&&(document.location=L.url)}function Cd(a){var b=-1,c=j,d;a.state?(d=(b=a.state.index)||b===0?W.T[b]:j)?(c=a.state.position,xd(d,bd,c?new Gb(c.$,c.s,c.g):j,b,!0)):Ed(a.state.url):(b=ld(W,U),xd(U,bd,j,b))}
function wd(){var a=ib("rel","index","link")[0];return!a?j:t.Ia(a.href)}function Fd(a,b){if(!M.index&&!(T>=1))return j;if(M.index){var c=new O(M.index-1),d=T,e=L;return b?e:xd(e,c,a?Hb:j,d)}else return T>=1?(c=T-1,d=W.T[c],e=j,e=d.loaded?new O(d.e.length-1):ad,c=b?d:xd(d,e,a?Hb:j,c)):c=j,c}function Gd(){if(S===-1)return!N&&Fd(!0)?!0:!1;var a=S-1;if(a<0)return Fd(!0)?!0:!1;S=a;N=j;md=-1;G(document,"treesaver.pageschanged");return!0}
function Hd(){return M.index<L.e.length-1||T!==-1&&T<W.T.length-1}function Id(a){if(!Hd())return j;if(M.index<L.e.length-1){var b=new O(M.index+1),c=T,d=L;return a?d:xd(d,b,j,c)}else return T!==-1&&T<W.T.length-1?(b=T+1,c=W.T[b],a=a?c:xd(c,bd,j,b)):a=j,a}function Jd(){if(S===-1)return N===Hb?Id():!1;var a=S+1;if(a>=L.e[M.index].v)return L.e[M.index].J?Id():!1;S=a;N=j;md=1;G(document,"treesaver.pageschanged");return!0}
function Ed(a){var b=zc(a).anchor,c=W.get(Dc(a)),a=-1,d=j;return c.length!==0&&(c=c[0],a=ld(W,c),d=c.loaded&&b?new O(c.ab[b]||0):new O(0,b),a!==-1)?xd(c,d,j,a):!1}
function Kd(a){md=0;M.index===Infinity?M=new O(L.e.length-1):M.anchor&&(M=new O(L.ab[M.anchor]||0));Jc(L.e[M.index],a)&&(S=-1,nd=0);var b=[],c,d,e;if(S===-1&&(S=Mc(),S===-1))return b.length=3,b[1]=Ld(),b;c=S-1;if(c<0){if((d=Fd(!1,!0))&&d===L)Jc(d.e[M.index-1],a),b=Lc(d.e[M.index-1],c,-c);else if(d&&d.loaded&&d.e[d.e.length-1].J)b=Lc(d.e[d.e.length-1],c,-c);else for(d=0,e=-c;d<e;d+=1)b[d]=j;d=3+c;c=0}else d=3;b=b.concat(Lc(L.e[M.index],c,d));if(d=3-b.length)if((c=Id(!0))&&c===L)Jc(c.e[M.index+1],a),
b=b.concat(Lc(c.e[M.index+1],0,d));else if(c)c.loaded?(Jc(c.e[0],a),b=b.concat(Lc(c.e[0],0,d))):(c.load(),b.length=3);for(d=1,e=b.length;d<e;d+=1)b[d]||(b[d]=L.error?{M:wc.prototype.M,A:wc.prototype.A,j:qd,size:rd}:Ld());if((!N||N===Hb)&&b[1]&&b[1].Gb)N=b[1].Gb;nd||(a=L.e[M.index],nd=a.ma?a.ma.c:0);for(d=0;d<b.length;d+=1)for(a=d+1;a<b.length;a+=1)b[d]===b[a]&&(b[a]=b[d].F());return b}
function xd(a,b,c,d,e){var g=j,i=j,g=j;if(!a)return!1;g=a.Cb[b&&b.index||0]||j||!!b.anchor&&b.anchor;i=a.url+(g?"#"+g:"");g=a.path+(g?"#"+g:"");if(a.da(L)&&d!==T&&!M.da(b)){var n=L.e[b.index]||j;md=M.index>b.index?-1:1;M=b;N!==c&&(N=c,S=-1);S=-1;e?Md({index:d,url:i,position:c},a.u.title,g):Nd({index:d,url:i,position:c},a.u.title,g);G(document,"treesaver.pageschanged");G(document,"treesaver.articlechanged",{article:n});return!0}document.title=a.u.title||a.title;L=a;N!==c&&(N=c,S=-1);S=-1;M=b;if(a.loaded){if(a.error)t.ob()&&
(document.location=a.url)}else a.load();d||d===0?(md=T>d?-1:1,T=d):(md=0,T=ld(W,a));e?Md({index:d,url:i,position:c},a.u.title||"",g):Nd({index:d,url:i,position:c},a.u.title||"",g);G(document,"treesaver.pageschanged");G(document,"treesaver.documentchanged",{document:a,url:i,path:g});G(document,"treesaver.articlechanged",{article:L.e[b&&b.index||0]||j});return!0}function Ld(){return{M:wc.prototype.M,A:wc.prototype.A,j:od,size:pd}};function Od(a){this.C=jb(a,"data-requires")?a.getAttribute("data-requires").split(" "):j;A("scroll",a).forEach(vc);this.X=[];this.Aa=[];this.a=j;this.j=a.parentNode.innerHTML;this.size=new F(a);delete this.size.c;delete this.size.b;this.Da=j;this.p=!1;this.h=this.ub=this.z=j;this.ua=!1;this.tb=[];this.Q=!1;this.Va=this.Wa=this.Sa=this.nextPage=this.Za=this.r=j;this.Ua=[];this.wb=[];this.Ba=[];this.nb=[];this.La=[];this.fb=[]}
Od.prototype.M=function(){if(!this.p)this.p=!0,this.a=nb(this.j),this.z=A("viewer",this.a)[0],this.ub=A("pagewidth",this.a),this.nextPage=A("next",this.a),this.Sa=A("nextArticle",this.a),this.Wa=A("prev",this.a),this.Va=A("prevArticle",this.a),this.Ua=ib("data-template","position",j,this.a),this.wb=this.Ua.map(function(a){return a.innerHTML}),this.Ba=ib("data-template","index",j,this.a),this.nb=this.Ba.map(function(a){return a.innerHTML}),this.La=ib("data-template","currentdocument",j,this.a),this.fb=
this.La.map(function(a){return a.innerHTML}),this.X=A("scroll",this.a).map(function(a){return new sc(a)}),this.tb=A("menu",this.a),this.Za=A("sidebar",this.a),this.h=[],Pd.forEach(function(a){H(document,a,this)},this),this.ua=!1,Qd(this);return this.a};
Od.prototype.A=function(){if(this.p)Rd(),this.p=!1,Pd.forEach(function(a){K(document,a,this)},this),this.fb=this.La=this.nb=this.Ba=this.wb=this.Ua=this.Va=this.Wa=this.Sa=this.nextPage=this.Aa=this.X=this.Za=this.tb=this.ub=this.z=this.a=j,this.h.forEach(function(a){a&&a.A()}),this.Da=this.h=j};function Rd(){sa("selectPages");sa("animatePages")}var Pd="treesaver.index.updated,treesaver.pageschanged,treesaver.documentchanged,keydown,click,mousewheel,DOMMouseScroll".split(",");
Ga?Pd.push("touchstart","touchmove","touchend","touchcancel"):Pd.push("mouseover");
Od.prototype.handleEvent=function(a){switch(a.type){case "treesaver.pageschanged":return Sd(this);case "treesaver.index.updated":return pa(this.Wb,[],"updateTOC",this),Sd(this);case "treesaver.documentchanged":Td(this);Ud(this);break;case "mouseover":a.touches||Qd(this);break;case "touchstart":return Vd(this,a);case "touchmove":var b=this.ja;if(b)a.stopPropagation(),a.preventDefault(),b.Ob=p(),b.oc=a.touches[0].pageX,b.pc=a.touches[0].pageY,b.ic=b.Ob-b.startTime,b.O=b.oc-b.yc,b.va=b.pc-b.Ac,b.ia=
Math.min(a.touches.length,b.ia),b.Vb=b.ia===1&&Math.abs(b.O)>=30&&Math.abs(b.O)*2>Math.abs(b.va),b.R&&(b.hb||b.R.Lb||!b.Vb)?(b.hb=b.hb||b.R.Lb||Math.abs(b.va)>=30,uc(b.R,-b.O,-b.va)):b.ia===2?b.gb=a.touches[1].pageX-b.zc:(this.I=b.O,Wd(this,!0));break;case "touchend":var b=this.ja,c=!1;ra();this.ja=j;if(b){a.stopPropagation();a.preventDefault();if(b.hb)uc(b.R,-b.O,-b.va,!0);else if(b.ia===1)if(b.Ob)b.Vb&&((c=b.O>0?Gd():Jd())?this.Y():Qd(this));else{var b=Xd(a.target),c=this.Q||this.z.contains(b),
d=document.createEvent("MouseEvents");d.initMouseEvent("click",!0,!0,a.view,1,a.changedTouches[0].screenX,a.changedTouches[0].screenY,a.changedTouches[0].clientX,a.changedTouches[0].clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,j);b.dispatchEvent(d)&&c?this.ua?this.Y():Qd(this):c?this.Y():Qd(this);c=!0}else b.ia===2&&Math.abs(b.gb)>=30&&(b.O<0&&b.gb<0?c=Id():b.O>0&&b.gb>0&&(c=Fd()),c?this.Y():Qd(this));if(!c)this.Db=p(),this.I=0,Wd(this,ab)}break;case "touchcancel":ra();this.ja=j;break;case "keydown":a:if(this.Q)Yd(this),
a.preventDefault();else if(!Zd(a)){switch(a.keyCode){case 34:case 39:case 40:case 74:case 32:Jd();break;case 33:case 37:case 38:case 75:Gd();break;case 72:Fd();break;case 76:Id();break;default:c=f;break a}this.Y();a.preventDefault()}return c;case "click":return this.click(a);case "mousewheel":case "DOMMouseScroll":if(Zd(a))b=!0;else if(this.Q)Yd(this),a.preventDefault();else if(c=p(),!(this.Nb&&c-this.Nb<1500))this.Nb=c,c=a.wheelDelta?a.wheelDelta:a.detail?-a.detail:0,d=this.z.contains(Xd(a.target)),
c&&d&&(a.preventDefault(),a.stopPropagation(),c>0?Gd():Jd(),this.Y());return b}};function Zd(a){return a.ctrlKey||a.shiftKey||a.altKey||a.metaKey}
Od.prototype.click=function(a){if(this.Q)Yd(this),a.stopPropagation(),a.preventDefault();else{if(Zd(a))return!0;if(!("which"in a&&a.which!==1||a.button)){var b=Xd(a.target),c,d=!1,e=d=c=!1,g=j;this.tb.forEach(function(a){y(a,"menu-active")&&(e=a.contains(b),gb(a,"menu-active"))},this);(d=this.Za.some(function(a){return a.contains(b)}))||this.Za.forEach(function(a){$d(a)},this);if(this.h[0]&&this.h[0].a.contains(b))Gd(),c=!0;else if(this.h[2]&&this.h[2].a.contains(b))Jd(),c=!0;else for(d=this.h[1]&&
this.h[1].a.contains(b);!c&&b&&b!==X;){if(d)y(b,"zoomable")&&(c=ae(this,b));else if(y(b,"prev"))Gd(),c=!0;else if(y(b,"next"))Jd(),c=!0;else if(y(b,"prevArticle"))Fd(),c=!0;else if(y(b,"nextArticle"))Id(),c=!0;else if(y(b,"menu"))e||w(b,"menu-active"),c=!0;else if(y(b,"sidebar")||y(b,"open-sidebar"))(g=be(b))&&!ce(g)&&de(g),c=!0;else if(y(b,"close-sidebar")&&(g=be(b))&&ce(g))$d(g),c=!0;if(!c&&b.href&&b.nodeName.toLowerCase()!=="img"){if(b.getAttribute("target")==="lightbox"){b=b.parentNode;continue}c=
t.Ia(b.href);if(!Ed(c))return;c=!0}b=b.parentNode}c&&(a.stopPropagation(),a.preventDefault())}}};function Xd(a){a?a.nodeType!==1&&a.parentNode&&(a=a.parentNode||X):a=X;return a}
function Vd(a,b){var c=Xd(b.target);if(X.contains(Xd(b.target)))if(b.stopPropagation(),b.preventDefault(),a.Q&&!a.r.R)Yd(a);else{a.ja={startTime:p(),ic:0,yc:b.touches[0].pageX,Ac:b.touches[0].pageY,O:0,va:0,ia:b.touches.length};if(a.ja.ia===2)a.ja.zc=b.touches[1].pageX;a.X.concat(a.Aa).concat(a.r?a.r.R:[]).forEach(function(a){if(a.contains(c))this.ja.R=a},a);qa([],4E3)}}
function Qd(a){if(!a.ua)a.ua=!0,w(a.a,"active"),G(document,"treesaver.active");var b=a.Y,c=ha.idletimer;c?c.pb=p():ma(b,5E3,1,j,"idletimer",a)}Od.prototype.Y=function(){if(this.ua)this.ua=!1,gb(this.a,"active"),G(document,"treesaver.idle");sa("idletimer")};function de(a){G(document,"treesaver.sidebaractive",{sidebar:a});w(a,"sidebar-active")}function $d(a){ce(a)&&G(document,"treesaver.sidebarinactive",{sidebar:a});gb(a,"sidebar-active")}function ce(a){return y(a,"sidebar-active")}
function be(a){if(y(a,"sidebar"))return a;for(;(a=a.parentNode)!==j&&a.nodeType===1;)if(y(a,"sidebar"))return a;return j}
function ae(a,b){var c;c=parseInt(b.getAttribute("data-figureindex"),10);c=isNaN(c)?j:L.e[M.index].content.n[c];if(!c)return!1;a.Y();if(!a.Q){var d=ee(),e=fe,g,i,n,l=j;for(g=0,i=e.length;g<i;g+=1)if(n=e[g],n.ga()&&n.Pa(d)){l=n;break}a.r=l;if(!a.r)return!1;a.Q=!0;a.r.M();a.a.parentNode.appendChild(a.r.a)}a.r.a=a.r.a;E(a.r.a,"width",wb(a.a));E(a.r.a,"height",C(a.a));d=a.r;d.m=d.m;e=new F(d.m);e={c:e.c,b:e.b};n=Vb(c,e);g=wb(d.m.offsetParent);i=C(d.m.offsetParent);var h;d.m=d.m;if(d.p&&n){Pb(n.wa,d.m,
n.name);d.m.style.bottom="auto";d.m.style.right="auto";h=new F(d.m);n=h.c;l=h.b;if(c.Ya)n=Math.min(e.c,n),l=Math.min(e.b,l),E(d.m,"width",n),E(d.m,"height",l),vc(d.m.firstChild),d.R=new sc(d.m),tc(d.R);E(d.m,"left",(g-n-h.Ja)/2);E(d.m,"top",(i-l-h.N)/2);c=!0}else c=!1;return!c?(Yd(a),!1):!0}function Yd(a){if(a.Q)a.Q=!1,a.a.parentNode.removeChild(a.r.a),a.r.A(),a.r=j}Od.prototype.ga=function(){return!this.C?!0:fb(this.C,!0)};Od.prototype.Pa=function(a){return vb(this.size,a)};
function ge(a){a.Da={c:wb(a.z),b:C(a.z)}}function he(a){var b=Y.S;E(b.a,"width",a.c);E(b.a,"height",a.b);b.Da=j;ge(b);b.X.forEach(function(a){tc(a)});L&&(Sd(b),pa(b.Wb,[],"updateTOC",b))}function Td(a){var b=L.url;a.Ba.forEach(function(a){var d=ib("href",j,"a",a).filter(function(a){return t.Ia(a.href)===b}),e=[];d.length&&(e=q(a.children),e.forEach(function(a){d.some(function(b){return a.contains(b)})?w(a,"current"):gb(a,"current")}))});a.X.forEach(function(a){tc(a)})}
function Ud(a){a.Ua.forEach(function(a,c){a.innerHTML=Mustache.to_html(this.wb[c],{pagenumber:S+1||1,pagecount:M===ad?1:L.e[M.index].v||1,url:L.url,documentnumber:T+1||1,documentcount:W.T.length})},a)}function ie(a){a.La.forEach(function(a,c){a.innerHTML=Mustache.to_html(this.fb[c],L.u)},a)}function je(a){var b=nd;b&&a.ub.forEach(function(a){E(a,"width",b)},a)}function ke(a,b){a.nodeName==="BUTTON"?a.disabled=!b:b?gb(a,"disabled"):w(a,"disabled")}
function le(a){if(a.nextPage){var b=S!==-1?S<L.e[M.index].v-1?!0:L.e[M.index].J&&Hd():N===Hb?Hd():!1;a.nextPage.forEach(function(a){ke(a,b)},a)}}function me(a){if(a.Sa){var b=Hd();a.Sa.forEach(function(a){ke(a,b)},a)}}function ne(a){if(a.Wa){var b=S!==-1?S>=1?!0:!!M.index||T>=1:!N&&(!!M.index||T>=1);a.Wa.forEach(function(a){ke(a,b)},a)}}function oe(a){if(a.Va){var b=!!M.index||T>=1;a.Va.forEach(function(a){ke(a,b)},a)}}function Sd(a){pa(a.Ub,[],"selectPages",a)}
Od.prototype.Ub=function(){Rd();var a=md;pe(this,a);var b=this.h[0],c=this.h[1],d=this.h[2],e,g,i=Math.max(c.size.marginLeft,b?b.size.marginRight:0),n=Math.max(c.size.marginRight,d?d.size.marginLeft:0),l=this.I;c.a.setAttribute("id","currentPage");e=(this.Da.c-c.size.sa)/2;g=e+c.size.sa;this.W=[];this.W[1]=e-c.size.marginLeft;b&&(this.W[0]=e-i-(b.size.sa+b.size.marginLeft),b.a.setAttribute("id","previousPage"));d&&(this.W[2]=g+n-d.size.marginLeft,d.a.setAttribute("id","nextPage"));if(a!==0)this.Db=
p(),this.I=a===-1?d?this.W[1]-this.W[2]:0:b?this.W[1]-this.W[0]:0,l&&(this.I+=l);else if(!this.I)this.I=0;if(ab&&this.I)this.I=0;Wd(this,ab);Ud(this);ie(this);je(this);le(this);me(this);ne(this);oe(this)};Od.prototype.Wb=function(){sa("updateTOC");var a={children:W.children.map(function(a){return a.u})};this.Ba.forEach(function(b,c){b.innerHTML=Mustache.to_html(this.nb[c],a)},this);Td(this)};
function pe(a,b){var c=a.h;a.h=Kd(a.Da);c.forEach(function(a){a&&this.h.indexOf(a)===-1&&(a.a&&a.a.parentNode===this.z&&this.z.removeChild(a.a),a.A())},a);a.h.forEach(function(a){if(a)a.a||a.M(),a.a.parentNode!==this.z&&(b===-1?this.z.insertBefore(a.a,this.z.firstChild):this.z.appendChild(a.a)),this.Aa=a.X.concat(this.Aa||[]),this.Aa.forEach(function(a){tc(a)})},a)}
function Wd(a,b){var c=a.I;if(!b){qa(["animatePages"],400);var d=p(),d=!b?Math.max(0,(a.Db||0)+200-d)/200:1;c*=-Math.cos(d*Math.PI)/2+0.5;Math.abs(c)<5?(a.I=c=0,ra()):pa(a.Ub,[],"animatePages",a)}a.h.forEach(function(a,b){a&&a.a&&Ab(a.a,this.W[b]+c)},a)};function qe(a){A("container",a);this.C=jb(a,"data-requires")?a.getAttribute("data-requires").split(" "):j;this.j=a.parentNode.innerHTML;this.size=new F(a);delete this.size.c;delete this.size.b;this.p=!1;this.m=this.a=j}qe.prototype.M=function(){if(!this.p)this.p=!0,this.a=nb(this.j),this.m=A("container",this.a)[0];return this.a};qe.prototype.A=function(){if(this.p)this.p=!1,this.a=j};qe.prototype.Pa=function(a){return vb(this.size,a)};qe.prototype.ga=function(){return!this.C?!0:fb(this.C,!0)};var Y,re,fe;function se(){Y={orientation:0,size:{c:0,b:0}};kb(X);Y.la=te();Y.viewport=ue();re=ve();fe=we();if(!re.length)return!1;xe();oa(xe,[],"checkState");Fa&&!ye&&!Ta&&(H(window,"orientationchange",ze),na(function(){window.scrollTo(0,0)},100));return!0}function te(){if(ye)return X;else{var a=document.createElement("div");a.setAttribute("id","chromeContainer");X.appendChild(a);return a}}
function ue(){var a=ib("name","viewport","meta")[0];a||(a=document.createElement("meta"),a.setAttribute("name","viewport"),hb("head")[0].appendChild(a));return a}function ve(){var a=[];Vc("chrome").forEach(function(b){var c;c=b.getAttribute("data-requires");if(!c||fb(c.split(" ")))Y.la.appendChild(b),c=new Od(b),a.push(c),Y.la.removeChild(b)});return a}
function we(){var a=[];Vc("lightbox").forEach(function(b){var c;c=b.getAttribute("data-requires");if(!c||fb(c.split(" ")))Y.la.appendChild(b),c=new qe(b),a.push(c),Y.la.removeChild(b)});return a}function ze(){if(Y.orientation!==window.orientation)cb(),Y.orientation=window.orientation,Y.orientation%180?Y.viewport.setAttribute("content","width=device-height, height=device-width"):Y.viewport.setAttribute("content","width=device-width, height=device-height"),Fa&&!ye&&!Ta&&window.scrollTo(0,1)}
function ee(){return ye?{c:wb(X),b:C(X)}:((window.pageYOffset||window.pageXOffset)&&window.scrollTo(0,1),"innerWidth"in window?{c:window.innerWidth,b:window.innerHeight}:{c:document.documentElement.clientWidth,b:document.documentElement.clientHeight})}
function xe(){var a=ee(),b;if(a.b!==Y.size.b||a.c!==Y.size.c){Y.size=a;if(!Y.S||!Y.S.ga()||!Y.S.Pa(a)){b=re;var c,d,e,g=j;for(c=0,d=b.length;c<d;c+=1)if(e=b[c],e.ga()&&e.Pa(a)){g=e;break}b=g;if(!b)return;kb(Y.la);Y.S&&Y.S.A();Y.la.appendChild(b.M());Y.S=b}he(a)}};function Ae(){K(window,"unload",Ae);Dd();Fa&&!ye&&K(window,"orientationchange",ze);Y.S&&Y.S.A();fe=re=Y=j;Be()};var Z={na:{$a:"treesaver.ready"}};Z.vc=function(){return Z.jb};Z.loaded=function(){return Z.jc};Z.jb=!1;Z.jc=!1;Z.Xa=function(){if(!Z.jb)document.body?(Z.jb=!0,K(document,"DOMContentLoaded",Z),K(document,"readystatechange",Z),K(window,"load",Z),delete Z.kb,G(document,Z.na.$a)):pa(Z.Xa)};Z.vb=function(){if("readyState"in document)/complete|loaded/.test(document.readyState)&&Z.Xa();else{var a=document.getElementsByTagName("*").length;Z.kb?a===Z.kb&&Z.Xa():(Z.kb=a,na(Z.vb,100))}};
Z.handleEvent=function(a){/load|DOMContentLoaded/.test(a.type)?Z.Xa():Z.vb()};H(document,"DOMContentLoaded",Z);H(document,"readystatechange",Z);H(window,"load",Z);Z.vb();var Ce={"treesaver-init":{target:"treesaver-init-0.9.2.js",src:"init.js"},"treesaver-core":{target:"treesaver-core-0.9.2.js",src:"core.js"}};Ce.get=function(a){return Ce[a].target};Ce.get("treesaver-init");var De={},X,ye,td,Ee;function Be(){if(ye)X.innerHTML=Ee;else if(td)X.innerHTML=td;Fe();la();Pc=j;Nc=0;Oc=[];t.Bc();document.documentElement.className="js no-treesaver";document.documentElement.style.display="block"}function Fe(){sa("unboot");K(document,Z.na.$a,Ge);delete De.Tb;delete De.Kb}
function Ge(){De.Kb=!0;(X=document.getElementById("ts_container"))?(ye=!0,Ee=X.innerHTML):(ye=!1,X=document.body);td=document.body.innerHTML;kb(X);X.innerHTML='<div id="loading">Loading '+document.title+"...</div>";document.documentElement.style.display="block";He()}function He(){De.Tb&&De.Kb&&document.body&&(Fe(),H(window,"unload",Ae),(!se()||!sd())&&Ae())};var Ie,Je="pushState"in window.history;function Ke(){var a=document.location.href.indexOf("#");return a===-1?"":document.location.href.substr(a+1)}if(document.location.hash){var Le=Ke();Le.charAt(0)==="-"&&Le.length>=2&&document.location.replace(Le.substr(1))}function Nd(a,b,c){window.history.pushState(a,b,c)}function Md(a,b,c){window.history.replaceState(a,b,c)}
if(!Je){var Nd=function(a,b,c){Me(a,b,c,!1)},Md=function(a,b,c){Me(a,b,c,!0)},Ne=function(a){document.location.hash="#"+a},Oe=function(a){document.location.replace("#"+a)},Me=function(a,b,c,d){var e="-"+window.escape(c);Yc("history:"+e,{state:a,title:b});c===document.location.pathname&&(e="");Ie=e;d?Oe(e):Ne(e)},Pe=function(){var a=Ke();a!==Ie&&(a=(Ie=a)?Zc("history:"+a):{},"onpopstate"in window&&typeof window.onpopstate==="function"&&window.onpopstate.apply(window,[{state:a?a.state:j}]))},Qe=function(){return Ke()!==
Ie};if("onhashchange"in window&&!xa)window.onhashchange=Pe;else if(oa(function(){Qe()&&Pe()}),Ba==="msie"){var Re=document.createElement("iframe");document.documentElement.appendChild(Re);Qe=function(){var a=Re.contentWindow.document.body.innerHTML;if(a!==Ie)return document.location.hash="#"+(a||""),!0};Oe=function(a){var b=Re.contentWindow.document;if(a!==b.body.innerHTML)b.body.innerHTML=a;document.location.replace("#"+a)};Ne=function(a){var b=Re.contentWindow.document;b.open();b.write("<html><body>"+
a+"</body></html>");b.close();document.location.hash="#"+a}}};eval("/*@cc_on (function(a,b,c){while(b--)a.createElement(c[b])})(document,21,['abbr','article','aside','audio','canvas','details','figcaption','figure','footer','header','hgroup','mark','menu','meter','nav','output','progress','section','summary','time','video'])@*/");/*
 Copyright 2011 Filipe Fortes ( www.fortes.com ).
 Version: 0.1.

 Licensed under MIT and GPLv2.
*/
if(wa){document.documentElement.style.display="none";t.load();cb();var Se=function(){De.Tb=!0;He()},Te;a:{var Ue=document.getElementsByTagName("link"),Ve,We=Ue.length;for(Ve=0;Ve<We;Ve+=1)if(Ue[Ve].rel.toLowerCase().indexOf("resources")!==-1){Te=Ue[Ve].getAttribute("href");break a}Te=j}Te?Nc?Nc===Uc?Se():Oc.push(Se):(Nc=1,Oc=[Se],t.get(Te,Sc)):Se();Z.vc()?Ge():H(document,Z.na.$a,Ge);na(Be,5E3,[],"unboot")}da("treesaver.VERSION","0.9.2-131-g153c17f");var Cc={};da("treesaver.config",Cc);}());
